-- Retail Sales Data Analysis Project
-- Author: Belagala Charan

-- 1. View all records from the dataset

SELECT *
FROM sales_data;


-- 2. Calculate total revenue generated

SELECT SUM(sales_amount) AS total_revenue
FROM sales_data;


-- 3. Identify revenue generated by each product

SELECT product,
       SUM(sales_amount) AS total_revenue
FROM sales_data
GROUP BY product
ORDER BY total_revenue DESC;


-- 4. Find revenue generated by each category

SELECT category,
       SUM(sales_amount) AS total_revenue
FROM sales_data
GROUP BY category
ORDER BY total_revenue DESC;


-- 5. Identify which region generates the most sales

SELECT region,
       SUM(sales_amount) AS total_revenue
FROM sales_data
GROUP BY region
ORDER BY total_revenue DESC;


-- 6. Count number of orders per region

SELECT region,
       COUNT(order_id) AS total_orders
FROM sales_data
GROUP BY region;


-- 7. Identify monthly sales trends

SELECT MONTH(order_date) AS month,
       SUM(sales_amount) AS monthly_revenue
FROM sales_data
GROUP BY MONTH(order_date)
ORDER BY month;


-- 8. Identify the highest single sale

SELECT *
FROM sales_data
ORDER BY sales_amount DESC
LIMIT 1;


-- 9. Identify average sales per category

SELECT category,
       AVG(sales_amount) AS avg_sales
FROM sales_data
GROUP BY category;


-- 10. Find total orders for each product

SELECT product,
       COUNT(order_id) AS total_orders
FROM sales_data
GROUP BY product
ORDER BY total_orders DESC;
